//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria()
        {
            this.Web_Validacion = new HashSet<Web_Validacion>();
        }
    
        public long categoria_id { get; set; }
        public byte numero { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public long estado_rips_id { get; set; }
        public bool tipo1 { get; set; }
        public bool tipo2 { get; set; }
        public bool tipo3 { get; set; }
        public bool tipo4 { get; set; }
        public bool tipo5 { get; set; }
        public bool tipo6 { get; set; }
        public bool tipo7 { get; set; }
        public bool tipo8 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Web_Validacion> Web_Validacion { get; set; }
        public virtual Estado_RIPS Estado_RIPS { get; set; }
    }
}
