//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directorios
    {
        public long directorios_id { get; set; }
        public string directorio_entrada { get; set; }
        public string directorio_salida { get; set; }
        public string directorio_error { get; set; }
        public string directorio_rechazo { get; set; }
        public string usuario_directorios { get; set; }
        public string contraseña_directorios { get; set; }
    }
}
