//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIVIPOLA
    {
        public long divipola_id { get; set; }
        public byte numero_departamento { get; set; }
        public short numero_municipio { get; set; }
        public string nombre_departamento { get; set; }
        public string nombre_municipio { get; set; }
        public bool urbana { get; set; }
        public bool rural { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    }
}
