//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodos_Reporte
    {
        public long periodos_reporte_id { get; set; }
        public System.DateTime fecha_minima { get; set; }
        public System.DateTime fecha_maxima { get; set; }
        public System.DateTime fecha_reporte { get; set; }
        public long FK_periodos_rol_id { get; set; }
        public long FK_periodos_estado_rips_id { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        public virtual Estado_RIPS Estado_RIPS { get; set; }
        public virtual Web_Rol Web_Rol { get; set; }
    }

    public partial class Periodos_Reporte1
    {
        public long periodos_reporte_id { get; set; }
        public System.DateTime fecha_minima { get; set; }
        public System.DateTime fecha_maxima { get; set; }
        public System.DateTime fecha_reporte { get; set; }
        public long FK_periodos_rol_id { get; set; }
        public long FK_periodos_estado_rips_id { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    }
}
