//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio_Radicacion
    {
        public long servicio_radicacion_id { get; set; }
        public Nullable<long> servicio_validacion_id { get; set; }
        public int radicado { get; set; }
        public Nullable<long> radicacion_estado_id { get; set; }
        public Nullable<System.DateTime> radicacion_fecha { get; set; }
        public string radicacion_usuario { get; set; }
        public Nullable<long> carga_estado_id { get; set; }
        public Nullable<System.DateTime> carga_fecha { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        public virtual Estado_RIPS Estado_RIPS { get; set; }
        public virtual Servicio_Validacion Servicio_Validacion { get; set; }
    }
}
