//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicio_Validacion_Error
    {
        public long servicio_validacion_error_id { get; set; }
        public long validacion_id { get; set; }
        public long estructura_id { get; set; }
        public long tipo_error_id { get; set; }
        public int cantidad { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        public virtual Servicio_Validacion Servicio_Validacion { get; set; }
        public virtual Estructura Estructura { get; set; }
    }
}
