//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Radicacion
    {
        public int radicado { get; set; }
        public Nullable<long> servicio_validacion_id { get; set; }
        public long servicio_radicacion_id { get; set; }
        public string estado_validacion { get; set; }
        public string estado_radicado { get; set; }
        public string estado_carga { get; set; }
        public string categoria { get; set; }
        public string afiliacion { get; set; }
        public string condicion { get; set; }
        public string entidad_reporta { get; set; }
        public string prestador { get; set; }
        public Nullable<long> administradora_id { get; set; }
        public Nullable<System.DateTime> periodo_inicio { get; set; }
        public Nullable<System.DateTime> periodo_fin { get; set; }
        public Nullable<int> us { get; set; }
        public Nullable<int> af { get; set; }
        public Nullable<int> ac { get; set; }
        public Nullable<int> ap { get; set; }
        public Nullable<int> au { get; set; }
        public Nullable<int> ah { get; set; }
        public Nullable<int> an { get; set; }
        public Nullable<int> am { get; set; }
        public Nullable<int> at { get; set; }
        public Nullable<System.DateTime> validacion_fecha { get; set; }
        public Nullable<System.DateTime> radicacion_fecha { get; set; }
        public Nullable<System.DateTime> carga_fecha { get; set; }
        public string usuario_validacion { get; set; }
        public string radicacion_usuario { get; set; }
    }
}
