//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Seguimiento_Web
    {
        public long Preradicado { get; set; }
        public Nullable<int> Radicado { get; set; }
        public string Tipo_Usuario { get; set; }
        public string Categoria { get; set; }
        public Nullable<System.DateTime> Periodo_inicio { get; set; }
        public Nullable<System.DateTime> Periodo_Fin { get; set; }
        public System.DateTime Fecha_Carga { get; set; }
        public long FK_usuario { get; set; }
        public long FK_estado_preradicacion { get; set; }
        public string Estado_Preradicacion { get; set; }
        public string Estado_Preradicacion_Descripcion { get; set; }
        public Nullable<long> validacion_id { get; set; }
        public Nullable<long> FK_estado_validacion { get; set; }
        public string Estado_Validacion { get; set; }
        public string Estado_Validacion_Descripcion { get; set; }
        public Nullable<long> radicacion_id { get; set; }
        public Nullable<long> FK_estado_radicacion { get; set; }
        public string Estado_Radicacion { get; set; }
        public string Estado_Radicacion_Descripcion { get; set; }
        public Nullable<long> estado_id { get; set; }
        public string Estado { get; set; }
    }
}
