//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Nivel_Permiso
    {
        public long nivelpermiso_id { get; set; }
        public long FK_nivelpermiso_rol { get; set; }
        public long FK_nivelpermiso_modulo { get; set; }
        public bool nivelpermiso_crear { get; set; }
        public bool nivelpermiso_modificar { get; set; }
        public bool nivelpermiso_eliminar { get; set; }
        public long FK_nivelpermiso_estado_rips { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        public virtual Web_Modulo Web_Modulo { get; set; }
        public virtual Estado_RIPS Estado_RIPS { get; set; }
        public virtual Web_Rol Web_Rol { get; set; }
    }
}
