//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Web_Usuario()
        {
            this.Web_Validacion = new HashSet<Web_Validacion>();
        }
    
        public long usuario_id { get; set; }
        public long FK_usuario_prestador { get; set; }
        public string correo { get; set; }
        public byte[] contrasenia { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string razon_social { get; set; }
        public string imagen { get; set; }
        public bool confirmacion_condiciones { get; set; }
        public Nullable<bool> confirmacion_correo { get; set; }
        public long FK_usuario_rol { get; set; }
        public long FK_usuario_estado_rips { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Web_Validacion> Web_Validacion { get; set; }
        public virtual Web_Rol Web_Rol { get; set; }
        public virtual Estado_RIPS Estado_RIPS { get; set; }
        public virtual Prestador Prestador { get; set; }
    }
}
