//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Preradicacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Web_Preradicacion()
        {
            this.Servicio_Validacion = new HashSet<Servicio_Validacion>();
        }
    
        public long preradicacion_id { get; set; }
        public Nullable<long> FK_web_preradicacion_web_validacion { get; set; }
        public long FK_preradicacion_estado_rips { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        public virtual Estado_RIPS Estado_RIPS { get; set; }
        public virtual Estado_RIPS Estado_RIPS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio_Validacion> Servicio_Validacion { get; set; }
        public virtual Web_Validacion Web_Validacion { get; set; }
    }
}
