//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips_V2.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_RolHasPermiso
    {
        public long rolhaspermiso_id { get; set; }
        public long FK_rolhaspermiso_rol { get; set; }
        public long FK_rolhaspermiso_permiso { get; set; }
        public long FK_rolhaspermiso_estado_rips { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        public virtual Web_Permiso Web_Permiso { get; set; }
        public virtual Web_Rol Web_Rol { get; set; }
        public virtual Estado_RIPS Estado_RIPS { get; set; }
    }
}
